worktree-path = "~/worktrees/{{ repo }}/{{ branch | sanitize }}"

[projects."github.com/IndieCampers/goindie-website"]
pre-start = [{ copy-env = '$HOME/.config/worktrunk/copy-env.sh {{ primary_worktree_path }}' }, { setup = 'eval "$(fnm env --shell bash)" && fnm use --install-if-missing && yarn install && yarn fetch-unzip-translations' }]
