/**
 * Step 3 of the curriculum build. Writes ../words.ts: starter phrases first,
 * then translated frequency candidates, until `total` words. Pronunciation
 * comes from Portugal IPA; a candidate without usable IPA or with a `-`
 * translation is dropped rather than guessed.
 *
 * Usage: node emit.ts <candidates.json> <uk.tsv> <kaikki-Portuguese.jsonl> <total>
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { type Candidate, type Entry, readEntries } from "./extract.ts";
import { ipaToCyrillic } from "./ipa.ts";
import { STARTER } from "./starter.ts";

interface Row {
	readonly pt: string;
	readonly uk: string;
	readonly ipa: string | undefined;
	readonly say: string;
}

export type Rejection = "untranslated" | "junk" | "no-ipa" | "bad-ipa" | "duplicate";

export function parseTranslations(tsv: string): ReadonlyMap<string, string> {
	const translations = new Map<string, string>();
	for (const line of tsv.split("\n")) {
		const [pt, uk, ...rest] = line.split("\t");
		if (pt === undefined || uk === undefined || rest.length > 0 || pt.trim() === "") {
			continue;
		}
		translations.set(pt.trim(), uk.trim());
	}
	return translations;
}

export function rowOf(candidate: Candidate, uk: string | undefined): Row | Rejection {
	if (uk === undefined || uk === "") {
		return "untranslated";
	}
	if (uk === "-") {
		return "junk";
	}
	if (candidate.ipa === undefined) {
		return "no-ipa";
	}
	const reading = ipaToCyrillic(candidate.ipa);
	return reading.ok ? { pt: candidate.pt, uk, ipa: candidate.ipa, say: reading.say } : "bad-ipa";
}

function isCandidate(value: unknown): value is Candidate {
	if (typeof value !== "object" || value === null) {
		return false;
	}
	const record: Record<string, unknown> = { ...value };
	return typeof record.pt === "string" && (record.ipa === undefined || typeof record.ipa === "string");
}

async function main(): Promise<void> {
	const [candidatesPath, ukPath, kaikkiPath, totalArg] = process.argv.slice(2);
	if (candidatesPath === undefined || ukPath === undefined || kaikkiPath === undefined || totalArg === undefined) {
		throw new Error("usage: node emit.ts <candidates.json> <uk.tsv> <kaikki.jsonl> <total>");
	}
	const total = Number.parseInt(totalArg, 10);
	const parsed: unknown = JSON.parse(readFileSync(candidatesPath, "utf8"));
	const candidates = Array.isArray(parsed) ? parsed.filter(isCandidate) : [];
	const translations = parseTranslations(readFileSync(ukPath, "utf8"));

	const starterIpa = new Map<string, Entry[]>();
	const starterIds = new Set(STARTER.map((word) => word.pt));
	await readEntries(kaikkiPath, (word) => starterIds.has(word), starterIpa);

	const rows: Row[] = STARTER.map((word) => {
		const ipa = starterIpa.get(word.pt)?.find((entry) => entry.ipa !== undefined)?.ipa;
		const reading = ipa === undefined ? undefined : ipaToCyrillic(ipa);
		return reading?.ok === true ? { pt: word.pt, uk: word.uk, ipa, say: reading.say } : { pt: word.pt, uk: word.uk, ipa: undefined, say: word.say };
	});
	const seen = new Set(rows.map((row) => row.pt));
	const rejected = new Map<Rejection, number>();
	for (const candidate of candidates) {
		if (rows.length >= total) {
			break;
		}
		const row = seen.has(candidate.pt) ? "duplicate" : rowOf(candidate, translations.get(candidate.pt));
		if (typeof row === "string") {
			rejected.set(row, (rejected.get(row) ?? 0) + 1);
			continue;
		}
		seen.add(row.pt);
		rows.push(row);
	}

	const body = rows.map((row) => `\tword(${JSON.stringify(row.pt)}, ${JSON.stringify(row.uk)}, ${row.ipa === undefined ? "undefined" : JSON.stringify(row.ipa)}, ${JSON.stringify(row.say)}),`).join("\n");
	const source = `/**
 * GENERATED by generate/emit.ts — do not edit by hand; edit generate/starter.ts
 * or rerun the build (see generate/README.md).
 *
 * ${rows.length} European Portuguese words: starter phrases, then subtitle
 * frequency order. \`ipa\` is Wiktionary Portugal IPA; \`say\` is a Ukrainian Cyrillic reading of Portugal IPA:
 * \`́\` marks stress, \`(н)\` marks a nasal vowel.
 */

import { type Word, wordId } from "./core.ts";

const word = (pt: string, uk: string, ipa: string | undefined, say: string): Word => ({ id: wordId(pt), uk, ipa, say });

export const WORDS: readonly Word[] = [
${body}
];
`;
	writeFileSync(path.join(import.meta.dirname, "..", "words.ts"), source);
	console.log(`${rows.length} words written; rejected: ${JSON.stringify(Object.fromEntries(rejected))}`);
}

if (import.meta.main) {
	await main();
}
