/**
 * Hand-picked starter words and set phrases for a total beginner, shown before
 * the frequency list. `say` here is a fallback only: emit.ts replaces it with
 * the Wiktionary Portugal IPA reading when one exists.
 */

export interface StarterWord {
	readonly pt: string;
	readonly uk: string;
	readonly say: string;
}

const word = (pt: string, uk: string, say: string): StarterWord => ({ pt, uk, say });

export const STARTER: readonly StarterWord[] = [
	word("olá", "привіт", "ола́"),
	word("obrigado", "дякую (каже чоловік)", "обріґа́ду"),
	word("obrigada", "дякую (каже жінка)", "обріґа́да"),
	word("por favor", "будь ласка", "пур фаво́р"),
	word("sim", "так", "сі(н)"),
	word("não", "ні", "на́у(н)"),
	word("bom dia", "доброго ранку", "бо(н) ді́а"),
	word("boa tarde", "добрий день", "бо́а тард"),
	word("boa noite", "добрий вечір; на добраніч", "бо́а нойт"),
	word("adeus", "до побачення", "аде́уш"),
	word("até logo", "до зустрічі", "ате́ ло́ґу"),
	word("até amanhã", "до завтра", "ате́ аменья́(н)"),
	word("desculpe", "вибачте", "дешку́лп"),
	word("com licença", "перепрошую (дозвольте пройти)", "ко(н) лісе́(н)са"),
	word("de nada", "нема за що", "де на́да"),
	word("tudo bem?", "як справи?", "ту́ду бай(н)"),
	word("está bem", "гаразд", "шта бай(н)"),
	word("não faz mal", "нічого страшного", "на́у(н) фаж мал"),
	word("pois", "ага, точно (згода)", "пойш"),
	word("se calhar", "мабуть", "се каля́р"),
	word("eu", "я", "е́у"),
	word("tu", "ти", "ту"),
	word("você", "ви (ввічливо)", "восе́"),
	word("ele", "він", "ел"),
	word("ela", "вона", "е́ла"),
	word("nós", "ми", "нош"),
	word("eles", "вони", "е́лш"),
	word("ser", "бути (постійна ознака)", "сер"),
	word("estar", "бути (стан, місце)", "шта́р"),
	word("ter", "мати", "тер"),
	word("fazer", "робити", "фазе́р"),
	word("ir", "йти, їхати", "ір"),
	word("vir", "приходити", "вір"),
	word("poder", "могти", "пуде́р"),
	word("querer", "хотіти", "кере́р"),
	word("saber", "знати (факт)", "сабе́р"),
	word("conhecer", "знати (людину, місце)", "куньюсе́р"),
	word("dizer", "казати", "дізе́р"),
	word("ver", "бачити", "вер"),
	word("dar", "давати", "дар"),
	word("falar", "говорити", "фала́р"),
	word("comer", "їсти", "куме́р"),
	word("beber", "пити", "бебе́р"),
	word("dormir", "спати", "дурмі́р"),
	word("trabalhar", "працювати", "трабалья́р"),
	word("gostar de", "подобатися", "гушта́р де"),
	word("precisar de", "потребувати", "пресіза́р де"),
	word("pensar", "думати", "пе(н)са́р"),
	word("abrir", "відкривати", "абрі́р"),
	word("fechar", "закривати", "фша́р"),
	word("comprar", "купувати", "ко(н)пра́р"),
	word("pagar", "платити", "паґа́р"),
	word("esperar", "чекати", "шпера́р"),
	word("começar", "починати", "кумеса́р"),
	word("acabar", "закінчувати", "акаба́р"),
	word("ajudar", "допомагати", "ажуда́р"),
	word("o que", "що", "у ке"),
	word("quem", "хто", "кай(н)"),
	word("onde", "де", "о́(н)д"),
	word("quando", "коли", "куа́(н)ду"),
	word("como", "як", "ко́му"),
	word("porquê", "чому", "пурке́"),
	word("porque", "тому що", "пу́рке"),
	word("quanto", "скільки", "куа́(н)ту"),
	word("hoje", "сьогодні", "ож"),
	word("amanhã", "завтра", "аменья́(н)"),
	word("ontem", "вчора", "о́(н)тай(н)"),
	word("agora", "зараз", "аґо́ра"),
	word("depois", "потім", "депо́йш"),
	word("antes", "раніше", "а́(н)тш"),
	word("sempre", "завжди", "се́(н)пр"),
	word("nunca", "ніколи", "ну́(н)ка"),
	word("já", "вже", "жа"),
	word("ainda", "ще", "аі́(н)да"),
	word("aqui", "тут", "акі́"),
	word("ali", "там", "алі́"),
	word("muito", "дуже; багато", "му́йнту"),
	word("pouco", "мало", "по́ку"),
	word("mais", "більше", "майш"),
	word("menos", "менше", "ме́нуш"),
	word("bem", "добре", "бай(н)"),
	word("mal", "погано", "мал"),
	word("também", "також", "та(н)бай(н)"),
	word("só", "тільки", "со"),
	word("com", "з", "ко(н)"),
	word("sem", "без", "сай(н)"),
	word("para", "для; до", "па́ра"),
	word("então", "тож, отже", "е(н)та́у(н)"),
	word("casa", "дім", "ка́за"),
	word("água", "вода", "а́ґуа"),
	word("café", "кава", "кафе́"),
	word("pão", "хліб", "па́у(н)"),
	word("comida", "їжа", "кумі́да"),
	word("pequeno-almoço", "сніданок", "пеке́ну алмо́су"),
	word("almoço", "обід", "алмо́су"),
	word("jantar", "вечеря", "жа(н)та́р"),
	word("sumo", "сік", "су́му"),
	word("gelado", "морозиво", "жела́ду"),
	word("a conta", "рахунок (у кафе)", "а ко́(н)та"),
	word("casa de banho", "туалет", "ка́за де ба́нью"),
	word("rua", "вулиця", "ру́а"),
	word("cidade", "місто", "сіда́д"),
	word("comboio", "поїзд", "ко(н)бо́йу"),
	word("autocarro", "автобус", "аутока́ру"),
	word("carro", "машина", "ка́ру"),
	word("telemóvel", "мобільний телефон", "телемо́вел"),
	word("trabalho", "робота", "траба́лью"),
	word("dinheiro", "гроші", "дінья́йру"),
	word("dia", "день", "ді́а"),
	word("semana", "тиждень", "сема́на"),
	word("ano", "рік", "а́ну"),
	word("hora", "година", "о́ра"),
	word("tempo", "час; погода", "те́(н)пу"),
	word("pessoa", "людина", "песо́а"),
	word("amigo", "друг", "амі́ґу"),
	word("família", "сім'я", "фамі́лія"),
	word("filho", "син", "фі́лью"),
	word("criança", "дитина", "кріа́(н)са"),
	word("miúdo", "малий, дитина (розмовне)", "міу́ду"),
	word("homem", "чоловік", "о́май(н)"),
	word("mulher", "жінка", "мулье́р"),
	word("rapariga", "дівчина", "рапарі́ґа"),
	word("nome", "ім'я", "ном"),
	word("coisa", "річ", "ко́йза"),
	word("problema", "проблема", "прубле́ма"),
	word("praia", "пляж", "пра́йа"),
	word("mar", "море", "мар"),
	word("sol", "сонце", "сол"),
	word("chuva", "дощ", "шу́ва"),
	word("frio", "холодний", "фрі́у"),
	word("quente", "гарячий", "ке́(н)т"),
	word("grande", "великий", "ґра́(н)д"),
	word("pequeno", "малий", "пеке́ну"),
	word("novo", "новий", "но́ву"),
	word("velho", "старий", "ве́лью"),
	word("bom", "добрий", "бо(н)"),
	word("mau", "поганий", "мау"),
	word("bonito", "гарний", "буні́ту"),
	word("fácil", "легкий", "фа́сіл"),
	word("difícil", "важкий", "діфі́сіл"),
	word("certo", "правильно", "се́рту"),
	word("claro", "звісно", "кла́ру"),
	word("pronto", "готово; ну все (розмовне)", "про́(н)ту"),
	word("fixe", "класно (сленг)", "фіш"),
	word("um", "один", "у(н)"),
	word("dois", "два", "дойш"),
	word("três", "три", "треш"),
	word("quatro", "чотири", "куа́тру"),
	word("cinco", "п'ять", "сі́(н)ку"),
	word("seis", "шість", "сайш"),
	word("sete", "сім", "сет"),
	word("oito", "вісім", "о́йту"),
	word("nove", "дев'ять", "нов"),
	word("dez", "десять", "деш"),
	word("cem", "сто", "сай(н)"),
	word("mil", "тисяча", "міл"),
];
